### ISSUE TITLE
Form Submission Issues

### ISSUE THREAD

**Issue by localoneway** [CodyHouse/cd-modal-form-changelog#1]
Hello,

I have a modal form and I am trying to get it to submit to my email. I am having issues. I am trying to use emailjs, but the modal form will not let me add a form id. It returns null in the console when I try and getElementById. Nowhere on your website can I find a way to submit forms or Newsletter signups. Please advise on how I can get these to work.

Thank You,
Andrew

**Comment by claudia-romano** [comment]
Hi Andrew, in the modal window component there's no code preventing the form from having an id. There may be an issue with the custom code you are using for getting the form. 

To submit the form, you can listen to the `submit` event of the form. If you are having issues with emailjs, there may be something wrong either with your custom code or with emailjs. You could try opening an issue there.

I'm closing this issue as this is not related to the component. Cheers.
